version: "3"
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8085:80"
    links:
      - "php-72"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./:/var/www/html/

  php-72:
    build: ./docker-images/php-72
    container_name: php-72
    links:
      - "mysql:mysql"
      - "mailhog:mailhog"
    volumes:
      - ./:/var/www/html/

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'magento'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    volumes:
      - ./data/mysql:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"