version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx_desafio
    ports:
      - "8085:80"
    links:
      - "php"
    volumes:
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./:/var/www/html/

  php:
    build: ./docker/docker-images/php
    container_name: php_desafio
    links:
      - "mysql:mysql"
    volumes:
      - ./:/var/www/html/

  mysql:
    image: mysql:5.7
    container_name: mysql_desafio
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/data/mysql:/var/lib/mysql